[pytest]
filterwarnings =
    ignore::DeprecationWarning:imp
    ignore::DeprecationWarning:cffi._imp_emulation
    ignore::PendingDeprecationWarning:magic
    ignore::DeprecationWarning:pkg_resources
    ignore::DeprecationWarning:clamd
