name: frontend-publish

on:
  push:
    branches:
      - malcolm-build
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-publish.yml
    with:
      service: manager
      dockerfile: ./build/go/manager/Dockerfile
